### PR TITLE
BNH-30 Add a Role for Landlords

### PR DESCRIPTION
**Pull request by TomHanmer29**
Added new landlord role to enable easier checking in the future

### CODE REVIEW

**Comment by TomHanmer29** [comment]
I have not added new unit tests just yet but wanted to make sure the current ones worked on git as they previously didn't for some unknown reason

**Comment by BenRamchandani** [comment]
Code looks sensible. Good luck writing tests for ClaimsTransformer, if it's too much of a pain don't worry

**Comment by TomHanmer29** [comment]
I am struggling to write tests for ClaimsTransformer specifically, Having stepped through the code in debug mode I think most of it requires a googleId which I'm not sure there's a way to spoof properly inside a test. I think it might be better to just merge this branch in for now and potentially figure out adding tests as a later ticket

**Comment by BenRamchandani** [comment]
> I am struggling to write tests for ClaimsTransformer specifically, Having stepped through the code in debug mode I think most of it requires a googleId which I'm not sure there's a way to spoof properly inside a test. I think it might be better to just merge this branch in for now and potentially figure out adding tests as a later ticket

It should be possible to either make a ClaimsIdentity, or `Fake` one. You'd have to fake the DbContext as well. At some point you're just testing your mocks rather than your actual code though 😕 I'm happy for you to merge without, just delete the empty test files.

**Comment by TomHanmer29** [comment]
Have removed the empty test files!

**Review by BenRamchandani — APPROVED** [review]

**Pull request merged**
